name: tannerjf.co
description: Tanner J Ferguson
url: https://tannerjf.co
enforce_ssl: tannerjf.co
markdown: redcarpet
highlighter: pygments
permalink: /posts/:title
exclude: ['node_modules', 'sass', 'Gemfile', 'Gemfile.lock', 'gulpfile.js', 'package.json', 'bower.json', 'CNAME']